"""initial
Revision ID: fdbbc179a45f
Revises: 7a07fe27fc80
Create Date: 2025-11-29 20:26:09.030464
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fdbbc179a45f'
down_revision = '7a07fe27fc80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('road_network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('geometry', sa.Text(), nullable=True),
    sa.Column('base_capacity', sa.Integer(), nullable=True),
    sa.Column('roughness_index', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('roles', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('damage_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_lon', sa.Float(), nullable=True),
    sa.Column('avg_severity', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('road_segment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['road_segment_id'], ['road_network.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=True),
    sa.Column('start_lon', sa.Float(), nullable=True),
    sa.Column('end_lat', sa.Float(), nullable=True),
    sa.Column('end_lon', sa.Float(), nullable=True),
    sa.Column('resource_allocation', sa.Text(), nullable=True),
    sa.Column('emission_reduction_estimate', sa.Float(), nullable=True),
    sa.Column('road_segment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['road_segment_id'], ['road_network.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traffic_dynamics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('road_segment_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('flow_entropy', sa.Float(), nullable=True),
    sa.Column('congestion_state', sa.String(length=32), nullable=True),
    sa.Column('vehicle_count', sa.Integer(), nullable=True),
    sa.Column('average_speed', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['road_segment_id'], ['road_network.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traffic_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('road_segment_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_count_limit', sa.Integer(), nullable=True),
    sa.Column('density_limit', sa.Float(), nullable=True),
    sa.Column('alert_type', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['road_segment_id'], ['road_network.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('recipient_type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('template', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('delivery_status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('traffic_thresholds')
    op.drop_table('traffic_dynamics')
    op.drop_table('projects')
    op.drop_table('damage_clusters')
    op.drop_table('users')
    op.drop_table('road_network')
    # ### end Alembic commands ###
